// Minimal word list for Snake + Wordle
// Replace or expand with your full list later.
const WORD_LIST = [
  "ABOUT","ABOVE","ANGLE","APPLE","BRAVE",
  "BRICK","CABIN","CABLE","CHARM","CHESS",
  "CLEAN","CLOVE","CRANE","CROWN","DAIRY",
  "DELTA","DRIFT","EAGER","EARTH","FAITH",
  "FRAME","FROST","GAUGE","GLARE","GLIDE",
  "GLOVE","GRAPE","GRIND","GUARD","HONEY",
  "HUMID","IVORY","JELLY","JOLLY","KNIFE",
  "LAYER","LEMON","LIGHT","LINEN","MACRO",
  "MARCH","MERCY","METAL","MIGHT","MONEY",
  "MONTH","MORAL","MOTOR","NERVE","NINJA",
  "NOISE","NORTH","NUDGE","OCEAN","OLIVE",
  "OPERA","ORDER","PAINT","PAPER","PARTY",
  "PATCH","PEACH","PEARL","PILOT","PIXEL",
  "PLANT","PLATE","POINT","POWER","PRIDE",
  "PRIME","PRIZE","QUACK","QUEEN","QUILT",
  "RANCH","REACT","RIVER","ROBIN","ROUTE",
  "ROYAL","RUSTY","SAUCE","SCARF","SCOUT",
  "SHARE","SHEEP","SHELF","SHELL","SHINE",
  "SHIRT","SHORE","SMILE","SMITH","SMOKE",
  "SNACK","SNAKE","SOLID","SOUND","SPACE",
  "SPARK","SPEAR","SPICE","SPIKE","SPINE",
  "SPORT","STAFF","STAGE","STAMP","START",
  "STEEL","STORM","STRAW","SUGAR","SWIFT",
  "TABLE","TEACH","THORN","TIGER","TOWER",
  "TRACK","TRAIL","TRAIN","TRUCK","TRUST",
  "UNION","UNITY","URBAN","VAPOR","VIRAL",
  "VOTER","WATER","WEARY","WHEAT","WHEEL",
  "WIDER","WORLD","WORTH","YACHT","YEAST",
  "YIELD","ZEBRA"
];
window.WORD_LIST = WORD_LIST;   // ← expose for non-module scripts
