// Small demo word list; replace with a larger list for production.
const WORD_LIST = [
  "ABOUT","ABOVE","ANGLE","APPLE","BRAVE","BRICK","BRINE","CABIN","CABLE","CHARM","CHESS","CLEAN",
  "CLOVE","CRANE","CRONY","CROWN","DAIRY","DELTA","DRIFT","EAGER","EARTH","FAITH","FRAIL","FRAME",
  "FROST","GAUGE","GLARE","GLIDE","GLOVE","GRAPE","GRIND","GUARD","HABIT","HONEY","HUMID","IVORY",
  "JELLY","JOLLY","KNACK","KNIFE","LAYER","LEMON","LIGHT","LINEN","MACRO","MARCH","MERCY","METAL",
  "MIGHT","MIXER","MONEY","MONTH","MORAL","MOTOR","NERVE","NINJA","NOISE","NORTH","NUDGE","OCEAN",
  "OLIVE","OPERA","ORDER","PAINT","PAPER","PARTY","PATCH","PEACH","PEARL","PILOT","PIXEL","PLANT",
  "PLATE","POINT","POWER","PRIDE","PRIME","PRIZE","QUACK","QUEEN","QUILT","RANCH","REACT","RIVER",
  "ROBIN","ROUTE","ROYAL","RUSTY","SAUCE","SCARF","SCOUT","SHARE","SHEEP","SHELF","SHELL","SHINE",
  "SHIRT","SHORE","SMILE","SMITH","SMOKE","SNACK","SNAKE","SOLID","SOUND","SPACE","SPARK","SPEAR",
  "SPICE","SPIKE","SPINE","SPLIT","SPORT","STAFF","STAGE","STAMP","START","STEEL","STORM","STRAW",
  "SUGAR","SWIFT","TABLE","TEACH","THORN","TIGER","TOWER","TRACK","TRAIL","TRAIN","TRICK","TRUCK",
  "TRUST","UNION","UNITY","URBAN","VAPOR","VIRAL","VOTER","WATER","WEARY","WHEAT","WHEEL","WIDER",
  "WORLD","WORTH","YACHT","YEAST","YIELD","ZEBRA"
];
